### ISSUE TITLE
Mat/Mesh weirdness

### ISSUE THREAD

**Issue by henrychronowski** [henrychronowski/bucharest#13]
Either I'm stupid and don't know how materials work with meshes but I can't get a texture spread over the entire generated map no matter what I try. I am just trying to put a simple grid material on the mesh renderer and it seems to just select 1 pixel of colour from the material and apply it to the whole map.

This is being done right at the head of the dev branch.

**Comment by A-Waters** [comment]
@henrychronowski "this is being done right at the head of the dev branch"? 
Does this mean its working on the head of the dev branch and its not working on the mapgen branch?

**Comment by A-Waters** [comment]
Fixed on branch feature_mapgen
